# Generated by Django 4.0.4 on 2022-06-14 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stdentdetails',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
