# Generated by Django 4.0.4 on 2022-06-17 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0002_alter_stdentdetails_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='stdentdetails',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='stdentdetails',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='stdentdetails',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
