# Generated by Django 4.0.4 on 2022-06-20 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0003_stdentdetails_created_at_stdentdetails_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionDetails',
            fields=[
                ('application_no', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('section', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='RollnoDetails',
            fields=[
                ('rollno', models.IntegerField(primary_key=True, serialize=False)),
                ('app_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentapp.admissiondetails')),
            ],
        ),
    ]
